apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: cert-manager
  namespace: addons
spec:
  subscriptions:
    - chart:
        repoURL: https://charts.jetstack.io
        name: cert-manager
        semverConstraint: "*"
