---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: addons
spec:
  promotionPolicies:
    - stage: argocd
      autoPromotionEnabled: true
    - stage: cert-manager
      autoPromotionEnabled: true
    - stage: kargo
      autoPromotionEnabled: true
