apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo
  namespace: addons
spec:
  subscriptions:
    - chart:
        repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
        semverConstraint: "*"
