---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: argocd
  namespace: addons
spec:
  subscriptions:
    - chart:
        repoURL: https://argoproj.github.io/argo-helm
        name: argo-cd
        semverConstraint: "*"
